name = "Polfed"
uuid = "467b4f57-cce5-4b05-af51-83574939c5b4"
authors = ["RockClimbingRocks <rok123.pintar2@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
